name: alitamsniosmobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  autocomplete_textfield: ^1.7.3
  awesome_dialog: ^2.1.1
  awesome_notifications: ^0.6.21
  badges: ^2.0.3
  cached_network_image: ^2.5.1
  cupertino_icons: ^1.0.2
  custom_progress_dialog: ^1.0.5
  date_format: ^2.0.4
  email_auth: ^0.0.1+2
  favorite_button: ^0.0.4
  flare_splash_screen: ^4.0.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^9.5.3+1
  flutter_textfield_autocomplete: ^1.0.2
  flutter_typeahead: ^3.2.4
  flutter_vector_icons: ^0.2.1
  fluttertoast: ^8.0.9
  geocoding: ^2.0.1
  geolocator: ^7.6.2
  http: ^0.12.1
  image: ^3.0.8
  image_picker: ^0.6.5+3
  intl: null
  open_file: ^3.2.1
  otp_text_field: ^1.1.1
  path_provider: ^2.0.10
  pdf: ^3.6.4
  photo_view: ^0.13.0
  pin_code_fields: ^7.3.0
  pin_entry_text_field: ^0.1.4
  printing: ^5.3.0
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  quantity_input: ^1.0.2
  shared_preferences: ^2.0.13
  splashscreen: ^1.3.5

dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/text.png
    - assets/user.png
    - assets/bgatas.png
    - assets/bgrond.png
    - assets/smartphone.png
    - assets/delete.png
    - assets/wfh.png
    - assets/deliv.png
    - assets/document.png
    - assets/fingerprint.png
    - assets/finsh.png
    - assets/hrd.png
    - assets/surveyor.png
    - assets/logout.png
    - assets/workout.png
    - assets/hp.png
    - assets/bggroup.png
    - assets/videocalling.png
    - assets/workfromhome.png
    - assets/about.png
    - assets/sneeze.png
    - assets/choose.png
    - assets/fail.png
    - assets/faill.png
    - assets/satu.png
    - assets/dua.png
    - assets/tiga.png
    - assets/display.png
    - assets/location.png
    - assets/locations.png
    - assets/password.png
    - assets/whatsapp.png
    - assets/welcome_page.flr
    - assets/timerr.png
    - assets/logoalita.png
    - assets/profile.png
    - assets/display.png
    - assets/sick.png
    - assets/layoff.png
    - assets/bginput.png
    - assets/kasur.png
    - assets/resume.png
    - assets/report.png
    - assets/usserr.png
    - assets/fabbttn.png
    - assets/db.png
    - assets/splash.png
    - assets/cuti.png
    - assets/checkin.png
    - assets/survey.png
    - assets/wfh.png
    - assets/workout.png
    - assets/bedd.png
    - assets/badreview.png
    - assets/log.png
    - assets/orderdelivery.png
    - assets/product.png
    - assets/mall.png
    - assets/neural.png
    - assets/buyyer.png
    - assets/shops.png
    - assets/comfort.png
    - assets/springa.png
    - assets/super.png
    - assets/therao.png
    - assets/mkp.png
    - assets/pending.png
    - assets/dikirim.png
    - assets/diproses.png
    - assets/approved.png
    - assets/selesai.png
    - assets/pendingtext.png
    - assets/Rejected.png
    - assets/stampapprove.png
  

  fonts:
    - family: OpenSans
      fonts:
          - asset: assets/fonts/OpenSans.ttf
    - family: Montserrat
      fonts:
          - asset: assets/fonts/Nunito.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
